### ISSUE TITLE
图没有显示出来

### ISSUE THREAD

**Issue by ratiger** [swardsman/learning-q-sharp#2]
如第一章的

> ​ $\begin{bmatrix} 1 \ 0 \end{bmatrix}，\begin{bmatrix} 0 \ 1 \end{bmatrix}，\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{1}{\sqrt{2}} \end{bmatrix}，\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{-1}{\sqrt{2}} \end{bmatrix}\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{i}{\sqrt{2}} \end{bmatrix}$
> ​ 图1.1 态矢量

**Comment by siyu-npc** [comment]
你好，我在github上同时放了一份pdf文档，你可能没看到，想直接再给你发一份，但被退回了，好像你那边接收邮件的大小有限制。你在github上找一下吧，就在仓库里。




------------------ 原始邮件 ------------------
发件人:&nbsp;"fucingcode"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 中午12:01
收件人:&nbsp;"swardsman/learning-q-sharp"<learning-q-sharp@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[swardsman/learning-q-sharp] 图没有显示出来 (#2)




如第一章的
  
​ $\begin{bmatrix} 1 \ 0 \end{bmatrix}，\begin{bmatrix} 0 \ 1 \end{bmatrix}，\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{1}{\sqrt{2}} \end{bmatrix}，\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{-1}{\sqrt{2}} \end{bmatrix}\begin{bmatrix} \frac{1}{\sqrt{2}} \ \frac{i}{\sqrt{2}} \end{bmatrix}$
 ​ 图1.1 态矢量

**Comment by ratiger** [comment]
谢谢, 打扰了
